#!/bin/bash
###########################################################################
# Installation script for Rob's tweaked git settings and streamlined config
# See DASL git wiki for detailed setup and usage instructions for git and the
# DASL server.
# Author: Robert W. Ellenberg
############################################################################

#Initialization of misc vars and flags

#Check if working in Mingw32 windows environment vs. linux or mac
MINGW_STRING=`uname | grep "MINGW"`
if [[ ${#MINGW_STRING} == 0 ]]
then
    MINGW_CHECK=false
else
    MINGW_CHECK=true
fi

#Some useful functions for this script.
function whatsmyname() {
# look up your username in the passwd file, then strip out just the name and extraneous characters.
if [[ $MINGW_CHECK == false ]]
then
    getent passwd `whoami` | cut -d ':' -f 5 | sed 's/,//g'
else
    whoami | sed 's/\\/\n/g' | tail -n 1
fi
}

function readData(){
    #Find default full name from the current user's passwd entry, otherwise
    #keep the old entry.
    if [[ $FULLNAME == '' ]]
    then
        FULLNAME=`whatsmyname`
    fi
echo $FULLNAME
    if [[ $DASL_USER == '' ]]
    then
        #Choose the default name from the full name, stripped of whitespace and
        #converted to camel case.
        DASL_USER=`echo "$FULLNAME" | sed -e 's/\ //' -e 's/^\(.\)/\L\1/'`
    fi

    if [[ $EMAIL == '' ]]
    then
        #Strip email out of current .gitconfig
        EMAIL=`grep email ~/.gitconfig 2> /dev/null | sed 's/[\t ]/\n/g' | tail -n1`
    fi

    easyread "Please enter your full name" "$FULLNAME";FULLNAME=$REPLY
    easyread "Please enter your email address" "$EMAIL";EMAIL=$REPLY
    easyread "Now your DASL server user name" "$DASL_USER";DASL_USER=$REPLY
    
    if [[ ${#GITHUB_USER} == 0 ]]
    then
        GITHUB_USER=$DASL_USER
    fi
    easyread "Finally, your Github user name" "$DASL_USER";GITHUB_USER=$REPLY

    echo -e "\nFor read-only github URLs, would you like to use"
    read -p "Public Key authentication when attempting to push? [y/N]:" AUTH_METHOD

    echo "------------------------------------------------------------"
    echo "Your information as entered is as follows:"
    echo "Author Name         : $FULLNAME"
    echo "Email               : $EMAIL"
    echo "DASL User name      : $DASL_USER"
    echo "GitHub User name    : $GITHUB_USER"
    if [[ $AUTH_METHOD == 'Y' || $AUTH_METHOD == 'y' ]]
    then
        GITHUB_PUSH_URL="git@github.com:$GITHUB_USER\/"
        GITHUB_GENERIC_PUSH="git@github.com:"
    else
        GITHUB_PUSH_URL="https:\/\/$GITHUB_USER@github.com\/$GITHUB_USER\/"
        GITHUB_GENERIC_PUSH="https:\/\/$GITHUB_USER@github.com\/"
        AUTH_METHOD='N'
    fi
    echo -e "Use SSH Public Key Authentication for Github? $AUTH_METHOD\n" 
    read -p 'Are these correct? [Y/n]' DATAOK
}

function bashrc_source() {

local SOURCED_SEARCH=`grep $1 ~/.bashrc`

if [[ ${#SOURCED_SEARCH} == 0 ]]
then
    cp $1 ~/$1
    echo "source ~/$1" >> ~/.bashrc
fi
}

function easyread() {
if [[ $MINGW_CHECK == false ]]
then
    read -e -p "$1:" -i "$2"
else
    read -e -p "$1 [$2]:"
fi
#Copy default value into return field
if [[ $REPLY == '' ]]
then
    REPLY=$2
fi
}

###############################################################################
# Script section
###############################################################################

# Optionally install recommended git tools and accessories
INSTALL_APPS='N'
read -p 'Install recommended support applications? [y/N]' INSTALL_APPS
if [[ $INSTALL_APPS == 'Y' || $INSTALL_APPS == 'y'  && $MINGW_CHECK == false ]]
then
    sudo apt-get install git-core vim-gtk gitg gitk diffuse git-flow
fi

DATAOK='N'

while [[ $DATAOK == 'N' || $DATAOK == 'n' ]]
do
    readData
done

# Backup old git files for user
mv ~/.gitconfig ~/.gitconfig.old
mv ~/.gitignore ~/.gitignore.old
#Super ugly field replacement
#TODO: Store the user data in a table for future use, or be smarter about default values
echo "-------------------------------------------------------------"
echo "Generating .gitconfig file from your information..."
sed -e "s/<FIRST> <LAST>/$FULLNAME/g" -e "s/<EMAIL>/$EMAIL/g" -e "s/<DASL_USER>/$DASL_USER/g" -e "s/<GITHUB_USER>/$GITHUB_USER/g" -e "s/<GITHUB_PUSH_URL>/$GITHUB_PUSH_URL/g" -e "s/<GITHUB_GENERIC_PUSH>/$GITHUB_GENERIC_PUSH/g" .gitconfig_template > ~/.gitconfig

#TODO: pull down the latest git completion from the repo?
echo "Setting up bash completion, so that common git commands can be tab-completed at the prompt"
if [[ $MINGW_CHECK == false ]]
then
    #if wget is available, get the latest version from the repo
    wget https://raw.github.com/git/git/master/contrib/completion/git-completion.bash -O ~/.git-completion.bash
    wget https://raw.github.com/bobthecow/git-flow-completion/master/git-flow-completion.bash -O ~/.git-flow-completion.bash
else
    #TODO: Use curl to pull this down
    cp .git-completion_current.bash ~/.git-completion.bash
fi

# Setup Git Prompt (ignore for windows). This colored prompt showes
# useful information, like repo status.
if [[ $MINGW_CHECK == false ]]
then
    echo "Setting up colored bash prompt for git repositories..."
    bashrc_source ".git-prompt.bash"
fi

#Optionally set up tweaked gitignore file based on common exclusions
read -p "Use Rob's gitignore file? [Y/n]:" GITIGNORE_BASIC
if [[ $GITIGNORE_BASIC == 'Y' || $GITIGNORE_BASIC == 'y' || ${#GITIGNORE_BASIC} == 0 ]]
then
    cp .gitignore ~/.gitignore
fi

echo " "
echo "-------------------------------------------------------------"
echo " "
echo "Setup complete!"
echo " "
