#!/usr/bin/env python

import os
import sys
import subprocess as sp
import string

def getch():
     os.system("bash -c \"read -n 1\"")
 
if __name__ == '__main__':
    search_mask = 'refs/heads/{}'.format(sys.argv[1])
    # print "Searching for branches matching", search_mask
    p_raw = sp.check_output(['git','for-each-ref','--format="%(refname:short)"','{}'.format(search_mask)]).split('\n')
    p = [l.strip('\"') for l in p_raw if l]
    if p:
        print 'Found branches:'
        for l in p:
            print l
        proceed = raw_input("Delete branches?")
        if "y" in proceed.lower():
            for l in p:
                n = l.strip('\"')
                if not n:
                    continue
                print n
                if sp.call(['git','branch','-v','-D','{}'.format(n)]):
                    sys.exit(1)
        else:
            print "aborted..."
            sys.exit(1)
    else:
        sys.exit(1)

